### ISSUE TITLE
run.sh line 55: /share/tesla_ble_mqtt/private.pem: No such file or directory

### ISSUE THREAD

**Issue by baylanger** [raphmur/tesla-local-control-addon#1]
I stumble on this error... and noticed there was no tesla_ble_mqtt directory. To fix the issue I added a symlink:

```
# ls -l /share/
drwxr-xr-x    2 root     root          4096 Mar  3 21:40 nginx_proxy
drwxr-xr-x    2 root     root          4096 Jun 15 14:37 tesla
lrwxrwxrwx    1 root     root            12 Jun 15 14:34 tesla_ble_mqtt -> /share/tesla
```

I don't mind creating the PR but I just don't have time today to dig around and understand if `tesla_ble_mqtt` is hardcoded to the name of this project, if a symlink is better or not, etc but I might have time tomorrow todig around.

**Comment by raphmur** [comment]
Thanks,

In fact I did not test re-using the key generated with the Tesla HTTP Proxy addon.
Nice workaround.

The installation of the [tesla-local-control-addon](https://github.com/raphmur/tesla-local-control-addon) should create the directory if not exists. I just added a fix that will create the folder: https://github.com/raphmur/tesla-local-control-addon/commit/e326b07e9e4297187470921f083ba73c76fafc50.
Then you can symlink the keys or copy/paste.
