### ISSUE TITLE
set +e ; translations directory ; bashio::log & debug

### ISSUE THREAD

**Issue by baylanger** [raphmur/tesla-local-control-addon#13]
- #11 add missing set +e
- #12 add translations directory (allows in UI to have a full description)
- #9 use bashio::log , add debug & increase version to 0.0.6a

Not to face conflicts, merge in following order #11 -> #12 -> #9

**Comment by baylanger** [comment]
<img width="786" alt="2024-06-17_09-57-36" src="https://github.com/raphmur/tesla-local-control-addon/assets/5240348/21a649b9-ffcd-4560-a253-fb98ef741ee5">

**Comment by baylanger** [comment]
bashio::log - Somehow when logging with .green .yellow ... it doesn't put the timestamp.

log.info is in green so instead of using log.green , in some places might as well use log.info

I suggest we adjust those later.

**Comment by baylanger** [comment]
For #9 looking at bashio::log source code reveals the way to make the logging for debug work.

``ˋ
 function bashio::log.level() {
    local log_level=${1}

    # Find the matching log level
    case "$(bashio::string.lower "${log_level}")" in
        all)
            log_level="${__BASHIO_LOG_LEVEL_ALL}"
            ;;
        trace)
            log_level="${__BASHIO_LOG_LEVEL_TRACE}"
            ;;
        debug)
            log_level="${__BASHIO_LOG_LEVEL_DEBUG}"
            ;;
            
…
``ˋ

I have appt - you can merge and I can adjust in ~ 6hr

**Comment by raphmur** [comment]
Ok good thanks.
Maybe you can message me at: ra ph murr ay at g mail . com

**Comment by raphmur** [comment]
PR merged. Will fix logging progressively
