### ISSUE TITLE
Alignment with tesla_ble_mqtt_docker

### ISSUE THREAD

**Issue by iainbullock** [raphmur/tesla-local-control-addon#14]
I'll start some adjustments to my dev branch to align with your main, which will make it easier to merge if that's what we decide to do

**Comment by baylanger** [comment]
fYI I have 3 PRs ready to merge, you might prefer to wait for those before starting your work.

**Comment by iainbullock** [comment]
Thanks for letting me know. I'm on holiday at the moment so I'm just watching not doing much work on it

**Comment by raphmur** [comment]
PR merged.
@iainbullock indeed, Pierre (@baylanger) has contributed a lot (thanks).
We will merge when you are back.

Please join this: https://discord.com/invite/zkZktGFk so that we can exchange a bit more easily.
