### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by gjaegy** [raphmur/tesla-local-control-addon#15]
Hi,

I'm trying to install the package as HA extension but I'm facing some issue generating the key.

I've configured the VIN, the BLE mac, etc.

However I think the keys genetation fails for some reason, see the attached log.

Any idea?

Thanks a lot !

`
Listening to BLE
S*******************C presence detected
Connecting to MQTT server; subscribe topics tesla_ble/+ and homeassistant/status
Received MQTT message: tesla_ble/config generate_keys
Configuration generate_keys requested
Generating the private key
cat: can't open 'private.pem': No such file or directory
Generating the public key
read EC key
writing EC key
cat: can't open 'public.pem': No such file or directory
KEYS GENERATED. Next:
1/ Remove any previously deployed BLE keys from vehicle before deploying this one
2/ Wake the car up with your Tesla App
3/ Push the button Deploy Key
`

**Comment by baylanger** [comment]
Which version do you have? 0.0.7 might fix this as I was facing the same issue.

**Comment by baylanger** [comment]
Sorry for the confusion, 0.0.7 was Released minutes after you open this issue.

Not sure if you are familiar, but you can force a “check updates” in the add-on menu within Home Assistant. Once you’ve done that within ~15s the update should be available.

**Comment by raphmur** [comment]
Yes please do so. 0.0.7 fixed a bug with Key deployment (although not mentioned in the changelog)

**Comment by gjaegy** [comment]
OK I'll try that update, thanks for the quick answer. I'll keep you updated.

**Comment by gjaegy** [comment]
It's working for me, I have been able to generate the key, thanks a lot 👍
It took me several attempts to have the key being sent successfully to the car, despite having the Pi relatively close to the car, but it eventually worked and commands are now sent to the car as expected.

**Comment by gjaegy** [comment]
Tomorrow I'll try to update my solar production excess automation script to rely on the BLE commands rather than the regular ones. Let's see what happens !

**Comment by raphmur** [comment]
Thanks for the feedback
In addition, this way of setting the charge amps also allows to go below 5 amps. I could not do it through the API...

**Comment by gjaegy** [comment]
I was able to set the charge amps to a value lesser than 5 on my side...
BTW, do you think there is a way to request some data (current charging amps for instance) using the BLE API, or is it only aimed at sending actions ?

**Comment by iainbullock** [comment]
Tesla's BLE API doesn't provide this functionality

**Comment by raphmur** [comment]
> I was able to set the charge amps to a value lesser than 5 on my side... BTW, do you think there is a way to request some data (current charging amps for instance) using the BLE API, or is it only aimed at sending actions ?

See https://github.com/tesla-local-control/tesla_ble_mqtt_core/issues/25
