### ISSUE TITLE
Add-on starts and stops right away with no error

### ISSUE THREAD

**Issue by baylanger** [raphmur/tesla-local-control-addon#5]
Something isn't working right with 0.0.3zb aka 0.0.4 per the changelog. It just stops... I don't have time now to go over your changes, gotta go run some errands otherwise will try to check later.

```
/share/tesla_ble_mqtt already exists, existing keys can be reused
Sourcing functions
Setting up auto discovery for Home Assistant
Discard any unread MQTT messages
Initialize counter
Entering listening loop
Listening to MQTT
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

Before this happened, this error at start had shown up:
```
discovery.sh line 95 ... command not found
```
The log is gone from the console log :(   Perhaps the error happened because send_cmd_retry_delay and/or ble_mac had no value. I removed the ble_mac and restart didn't make this show up again... and trying to remove the send_cmd_retry_delay value sets it by default to 5.

**Comment by raphmur** [comment]
Yeah seen it.
I suspect something in HA side. It has happened suddenly... I am on it

**Comment by raphmur** [comment]
Should be fixed in latest commit and release https://github.com/raphmur/tesla-local-control-addon/releases/tag/v0.0.5

**Comment by baylanger** [comment]
After long troubleshooting, I noticed bash was just fine but bashio would fail. I was just about to add a `set +e` ... after noticing bashio by default sets `-e` !!

Thanx for the fix.

**Comment by raphmur** [comment]
Yes, went around to try and find the best place to put it.
It has been stable for 1hr so far
